config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/fitnews')
  devise_for :users
  resources :fitnews

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/fitnews.rb
class Fitnews < ActiveRecord::Base
	  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :fitnews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :email, :password, :firstname, :lastname, :birthday) }
  end
end

app/controllers/fitnews_controller.rb
class FitnewsController < ApplicationController
  before_action :set_fitnews, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :right_user, only: [:edit, :update, :destroy]
  # GET /fitnews
  # GET /fitnews.json
  def index
    @fitnews = Fitnews.all
  end

  # GET /fitnews/1
  # GET /fitnews/1.json
  def show
  end

  # GET /fitnews/new
  def new
    @fitnews = Fitnews.new
  end

  # GET /fitnews/1/edit
  def edit
  end

  # POST /fitnews
  # POST /fitnews.json
  def create
    params[:fitnews][:user_id]=current_user.id
    @fitnews = Fitnews.new(fitnews_params)

    respond_to do |format|
      if @fitnews.save
        format.html { redirect_to @fitnews, notice: 'Fitnews was successfully created.' }
        format.json { render :show, status: :created, location: @fitnews }
      else
        format.html { render :new }
        format.json { render json: @fitnews.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fitnews/1
  # PATCH/PUT /fitnews/1.json
  def update
    respond_to do |format|
      if @fitnews.update(fitnews_params)
        format.html { redirect_to @fitnews, notice: 'Fitnews was successfully updated.' }
        format.json { render :show, status: :ok, location: @fitnews }
      else
        format.html { render :edit }
        format.json { render json: @fitnews.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fitnews/1
  # DELETE /fitnews/1.json
  def destroy
    @fitnews.destroy
    respond_to do |format|
      format.html { redirect_to fitnews_index_url, notice: 'Fitnews was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fitnews
      @fitnews = Fitnews.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fitnews_params
      params.require(:fitnews).permit(:title, :content, :is_public, :user_id)
    end

    def right_user
      unless @fitnews.user_id == current_user.id
       redirect_to fitnews_index_url
    end

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fitnews_helper.rb
module FitnewsHelper
end

app/views/fitnews/_form.html.erb
<%= form_for(@fitnews) do |f| %>
  <% if @fitnews.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fitnews.errors.count, "error") %> prohibited this fitnews from being saved:</h2>

      <ul>
      <% @fitnews.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :is_public %><br>
    <%= f.check_box :is_public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fitnews/edit.html.erb
<h1>Editing Fitnews</h1>

<%= render 'form' %>

<%= link_to 'Show', @fitnews %> |
<%= link_to 'Back', fitnews_index_path %>

app/views/fitnews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fitnews</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Content</th>
      <th>Is public</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fitnews.each do |fitnew| %>
      <tr>
        <td><%= fitnew.id %></td>
        <td><%= fitnew.title %></td>
        <td><%= fitnew.content %></td>
        <td><%= fitnew.is_public %></td>
        <td><%= fitnew.user.try(:email) %></td>
        <td><%= link_to 'Show', fitnew %></td>
        <td><%= link_to 'Edit', edit_fitnews_path(fitnew) %></td>
        <td><%= link_to 'Destroy', fitnew, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fitnews', new_fitnews_path %>

app/views/fitnews/new.html.erb
<h1>New Fitnews</h1>

<%= render 'form' %>

<%= link_to 'Back', fitnews_index_path %>

app/views/fitnews/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @fitnews.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @fitnews.content %>
</p>

<p>
  <strong>Is public:</strong>
  <%= @fitnews.is_public %>
</p>

<%= link_to 'Edit', edit_fitnews_path(@fitnews) %> |
<%= link_to 'Back', fitnews_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fitbegin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Fitnews Corner</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/fitnews">Fitnews</a></li>
      </ul>
      <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
    </div>
  </div>
</nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    FitBeginProject
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>